#!/usr/bin/env bash
# Installs, configures, and starts the server
# Configure my Nginx server
#    so that /redirect_me is redirecting to another page.
#
# The redirection must be a “301 Moved Permanently”
# Using what i did with 1-install_nginx_web_server,
#       write 3-redirection so that it configures a brand new
#       Ubuntu machine to the requirements asked in this task
#
# Configures a new ubuntu machine by installing
#     Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Author Wycliffe Ochieng

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
