#!/usr/bin/env bash
# Start Apache so as to return a
# page conatining Hello Holberton
# run apache on designated container
# Author Wycliffe Omondi

echo "ServerName localhost" >> /etc/apache2.conf
service apache2 start
